### ISSUE TITLE
Segfaults when using Function keys literals

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/skhd#2]
Skhd segfaults when using function keys literals. Maybe I do not understand properly the syntax :(

Here's what happen:

```
❯❯❯ ~ skhd
skhd: using config '/Users/bigo/.skhdrc'
(#2) hotkey :: {
	mod: 'cmd'
	mod: 'alt'
	key: 'q' (12)
	cmd: 'brew services stop chunkwm'
}
(#5) hotkey :: {
	mod: 'cmd'
	mod: 'alt'
	key: 'r' (15)
	cmd: 'bash $HOME/.chunkwmrc'
}
(#8) hotkey :: {
	mod: 'cmd'
	mod: 'alt'
	key: 'k' (40)
	cmd: 'khd -e "reload"'
}
(#11) hotkey :: {
	mod: 'cmd'
	mod: 'alt'
	key: 'u' (32)
	cmd: 'bash -c "LPID=$(pgrep -f bersicht); kill $LPID; open -a Übersicht"'
}
(#14) hotkey :: {
	mod: 'ctrl'
	mod: 'shift'
	key: 'f' (3)
(#14:17) expected token 'Token_Command', but got '1'
[1]    9304 segmentation fault  skhd
```

And the config line causing the segfault is:

```
# block screen
ctrl + shift - f12                       :    m screensaver
```

**Comment by crisidev** [comment]
I have other lines using Function keys and they all behave the same.

**Comment by koekeishiya** [comment]
Oops, the lexer doesnt actually permit the format *\<char>\<digit>* (e.g:`f1`) will return the token `f`. The parser does handle it properly though, so it should be a quick fix.

https://github.com/koekeishiya/skhd/blob/master/src/tokenize.c#L62

You can use the keycode for the function keys til this gets fixed. 
See https://github.com/koekeishiya/khd/issues/1 or https://github.com/koekeishiya/cev for keycodes.

**Comment by koekeishiya** [comment]
should be fixed, but not on a macbook so have not tested.

**Comment by crisidev** [comment]
I will test it now. Thanks!

**Comment by crisidev** [comment]
Tested and the segfault is gone. 

There is still a problem with Function keys thou: they just do not work. All other shortcut works fine, the one with Function keys don't.

Running skhd from terminal and trying the Function keys shortcut prints stuff on the terminal and do no trigger the shortcut.

Example for cmd-f[1,2,3,4]:

```
...
(#117) hotkey :: {
	mod: 'cmd'
	mod: 'shift'
	mod: 'ctrl'
	mod: 'alt'
	key: '6' (22)
	cmd: 'chunkc tiling::window -d 12'
}
hotload: watching file '.skhdrc' in directory '/Users/bigo'
^[[17;2~^[[17;2~^[[17;2~^[[17;2~^[[17;2~^[OQ^[OQ^[OR^[[17;2~^C
```

**Comment by koekeishiya** [comment]
Hm does the keycode we generate for the function keys correspond to the ones here: https://cloud.githubusercontent.com/assets/6175959/18551554/35137fc6-7b59-11e6-81a0-bef19ed5db5e.png (unsure if we print the keycode in hexadecimal or integers, but you'll notice that quickly).

I remember having the same problem in khd when experimenting with function key as binds, and I had to also hold *fn* when doing said key.

**Comment by crisidev** [comment]
Holding FN nothing works.

Regarding the keycodes, it is weird.. They are not printing anything from the two keyboard type you posted.

Maybe it is worth to say I have setup to use Fn to for HW function keys.

**Comment by koekeishiya** [comment]
The values we print is in decimal, not hexadecimal. Not sure why I opted to do it that way. Give me a sec.

**Comment by crisidev** [comment]
Sure, no rush :D

**Comment by koekeishiya** [comment]
Hopefully it should be more readable now.

**Comment by crisidev** [comment]
Ok, now they are printed properly.

Mapping (i use from F1 to F5 and F18):
```
F1 - 0x7a
F2 - 0x7a
F3 - 0x7a 
F4 - 0x7a
F5 - 0x7a
F18 - 0x6d
```

All of them apart from F18 (which is remapped on ESC via Karabiner-Elements) are 0x7a

**Comment by koekeishiya** [comment]
Does khd properly run the function keys command? (just have khd load the skhd config)

**Comment by crisidev** [comment]
Yes it does.

**Comment by koekeishiya** [comment]
I believe it should be fixed now.

**Comment by crisidev** [comment]
Testing!

**Comment by crisidev** [comment]
Yayyyyy. Great job as usual!! All working fine and it is way more performant than khd.

**Comment by koekeishiya** [comment]
Glad it worked. Was afraid I'd have some stupid syntax error or forgetting to change a variable reference during the latter bigger changes, as I'm not on macOS.. I really should add a travis config at some point
